# Generated by Django 4.2.14 on 2024-08-05 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voicengerdb', '0003_chat_chatparticipant_message_remove_user_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='group_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('invite_link', models.URLField(blank=True, null=True)),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_in_chats', to='voicengerdb.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.groupchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicengerdb.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groupchat')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('Attachment', 'Attachment'), ('Photo', 'Photo'), ('Video', 'Video'), ('Link', 'Link'), ('VoiceMessage', 'VoiceMessage')], max_length=50)),
                ('file', models.FileField(upload_to='group_chat_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groupchat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicengerdb.user')),
            ],
        ),
    ]
