# Generated by Django 5.0.7 on 2024-07-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicengerdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('nickname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
