# Generated by Django 4.2.14 on 2024-08-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicengerdb', '0003_chat_chatparticipant_message_remove_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
