# Generated by Django 4.2.14 on 2024-08-14 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('voicengerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together=set(),
        ),
    ]
