# Generated by Django 4.2.14 on 2024-08-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('voicengerapp', '0002_alter_userchat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
