# Generated by Django 4.2.14 on 2024-08-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('voicengerapp', '0003_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, default='NewChat1', max_length=255, null=True),
        ),
    ]
