# Generated by Django 4.2.14 on 2024-08-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicengerapp', '0005_alter_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
